### ISSUE TITLE
关于用jittor读取torch pth文件可能的错误

### ISSUE THREAD

**Issue by Exusial** [Jittor/jittor#106]
最近使用jittor读取torch嵌套pth文件发现这样一个问题：一旦torch的sequential或者嵌套module带有名字，jittor就无法读取（和jittor sequential数字索引有关。）因此用户必须按照数字顺序命名。我自己尝试使用回溯来是的用户可以任意命名。
另外还有一个小bug：打印module时，其中的LeakyReLU层会显示MakeModule，查阅文档似乎ReLU系层都存在这个问题。

**Comment by cjld** [comment]
您好，请问可以提供一个可供复现的例子吗？
关于LeakyRelu层的问题，我们也将尽快修复

**Comment by Exusial** [comment]
在复现sinGAN时遇到这个问题，torch版本命名了sequential层。读取参数会报错。
另外还有一个问题：
bathchnorm层torch有一个追踪batch的参数，而jittor没有。该参数默认开启，因此jittor读取pth文件时若其中有batchnorm层的参数，也会报找不到属性的错误

**Comment by cjld** [comment]
batchnorm层的信息是黄字，不是错误是warning

**Comment by Exusial** [comment]
谢谢。目前看来都是可以通过用户操作避免警告的。

**Comment by wszhengjx** [comment]
请问当我加载用model.load()加载pth文件的时候出现错误“FIle is not a zipfile"怎么解决？
