### ISSUE TITLE
dirty_fix_pytorch_runtime_error似乎并不起作用

### ISSUE THREAD

**Issue by wuyangdut** [Jittor/jittor#126]
依次运行：
import jittor as jt
jt.dirty_fix_pytorch_runtime_error()
import torch
报错：munmap_chunk(): invalid pointer

这个问题导致python3.7 -m jittor.test -v没能通过，难道和我的系统是manjaro有关系吗

**Comment by cjld** [comment]
您好，感谢您的反馈，`dirty_fix_pytorch_runtime_error` 这个功能目前可以解决和pytorch 1.3的冲突问题，但是最新版本的pytorch还有问题。原因是因为pytorch直接吧整个mkl编译到了源码里面，然而pytorch没有做好全局符号管理，导致冲突。
这个问题我们正在尝试修复解决，只要不同时import torch和jittor，这个问题是不会触发的。
如果有同时import jittor和pytorch的需求，您可以试试安装pytorch1.3版本

**Comment by wuyangdut** [comment]
亲测torch1.6可行，无意中发现的

**Comment by cjld** [comment]
惊了，非常感谢！
