### ISSUE TITLE
About the correctness of EventQueue

### ISSUE THREAD

**Issue by yuanms2** [Jittor/jittor#144]
https://github.com/Jittor/jittor/blob/35b22799fda921b28e95b96d0b134fc1b2b90e7d/src/event_queue.h#L30

Hi, excellent work. I am studying the code of jittor. I am confused about the above line of code.
what will happen if I call the 'run' method several times before the previous 'todo' is executed? Will the new 'todo' overwrite the old one? 

thanks.

**Comment by cjld** [comment]
Thank you, `EventQueue::Worker::run` is a internal function, it will only be called once by `EventQueue::run_sync`

**Comment by yuanms2** [comment]
thanks, I see.
