### ISSUE TITLE
设置seed输出还是会有不同

### ISSUE THREAD

**Issue by jwzxgy2007** [Jittor/jittor#160]
你好，我在跑pointnet++的时候有一个问题，我设置了jt.seed()以及np.random.seed()，并且吧dataset的shuffle去掉了，但是输出仍然有所不同，这是前几个batch的loss，是否是我的设置问题还是存在bug?谢谢

![微信图片_20201206181501](https://user-images.githubusercontent.com/14820455/101277376-04130980-37ef-11eb-8c2c-dfc88d546e96.png)
![微信图片_20201206181515](https://user-images.githubusercontent.com/14820455/101277379-083f2700-37ef-11eb-9b4c-2fe4d30fb733.png)

**Comment by Gword** [comment]
您好，GPU运算本身具有一定的随机性，并发浮点数加法的顺序会略微影响精度，第一个iter的loss差别不大，是正常现象

**Comment by jwzxgy2007** [comment]
好的谢谢！

**Comment by maxint** [comment]
https://pytorch.org/docs/stable/notes/randomness.html
保持可复现不大容易呀，请问 jitter 有计划做这方面的工作的？

**Comment by Jittor** [comment]
您试试jt.set_global_seed()?
显卡并行计算会引入非常微小的随机性，这个也很难避免。



---原始邮件---
发件人: "Naiyang ***@***.***&gt;
发送时间: 2021年6月9日(周三) 下午2:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Jittor/jittor] 设置seed输出还是会有不同 (#160)




 
https://pytorch.org/docs/stable/notes/randomness.html
 保持可复现不大容易呀，请问 jitter 有计划做这方面的工作的？

**Comment by maxint** [comment]
嗯，我也是用了`jt.set_global_seed()`，不过还是有差异

**Comment by maxint** [comment]
不过暂时先这样，估计不大好解决，谢谢回复！
