### ISSUE TITLE
python -m jittor.test.test_example需要访问什么网站吗

### ISSUE THREAD

**Issue by wzzwh110** [Jittor/jittor#188]
我在使用python -m jittor.test.test_example的时候 出现了urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
这个问题 我想问一下在使用test_example需要访问什么url吗

**Comment by dlutzhouyue** [comment]
the same issue

**Comment by Jittor** [comment]
会访问github，下载一些相关的依赖包，比如mkl，如果是cuda的话还会下载cub等加速库，这些下载都是自动的，所以安装的时候请确保网络通畅，
如果网不好的话，也可以使用docker镜像离线下载：https://cg.cs.tsinghua.edu.cn/jittor/tutorial/2020-5-15-00-00-docker/#%E9%95%9C%E5%83%8F%E4%B8%8B%E8%BD%BD



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月19日(周六) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Jittor/jittor] python -m jittor.test.test_example需要访问什么网站吗 (#188)




 
the same issue
