### ISSUE TITLE
CUDA配置问题

### ISSUE THREAD

**Issue by iotsharer** [Jittor/jittor#2]
我用的是服务器，有GPU。由于没有管理员权限，有些东西配置不了，不过我可以正常安装使用Pytorch还有tensorflow的GPU操作等，希望进一步提升，安装的时候可以考虑到没有管理员权限情况。
![image](https://user-images.githubusercontent.com/29347606/77137105-79934a00-6aa7-11ea-9e26-a814b0f44c8c.png)

**Comment by Escapingbug** [comment]
看起来不止是管理员权限的问题，在选择查找 CUDA 文件的路径时直接采用了[硬编码](https://github.com/Jittor/jittor/blob/master/python/jittor/compile_extern.py#L144)，这样的话在其他 Linux 发行版上可能会无法正常工作？这个目录应该是 Ubuntu 系有的。

**Comment by cxjyxxme** [comment]
可以试试设置环境变量export nvcc_path=[cuda_path]/bin/nvcc，当这个环境变量为空时，我们会默认cuda在/usr/local/cuda

**Comment by Jittor** [comment]
如果没有权限可以尝试使用pip安装
