### ISSUE TITLE
What is the meaning of comments like "// @pyjt(...)" ?

### ISSUE THREAD

**Issue by xmyqsh** [Jittor/jittor#21]
What is the meaning of comments like "// @pyjt(...)", eg. "// @pyjt(grad)" ?

as well as:

"pynames": pynames, # names in @pyjt(...)
               "attrs": attrs, # attrs in @attrs(...)

**Comment by Gword** [comment]
Thanks for your feedback. @pyjt is an identifier that converts a c ++ interface to a python interface. E.g. 
`
// @pyjt (grad)
vector <VarHolder *> _grad (VarHolder * loss, const vector <VarHolder *> & targets);
`
_Grad function can be called using jt.grad in python. And pynames are alias of this interface，attrs are some attribute that control the python binding behaviors.

**Comment by xmyqsh** [comment]
```
232 reg = re.compile(
233     '(/\\*(.*?)\\*/\\s*)?(//\\s*@pyjt\\(([^\\n]*)\\)\\s*)'
234     # ^^^^^^^^^^^^^^^^^          ^^^^    ^^^^
235     # doc string $1              pyjt    args $3
236     +
237     '(//\\s*@attrs\\(([^\\n]*)\\)\\s*)?'
238     #        ^^^^^   ^^^^^^^
239     #        attrs    args $5
240 , re.DOTALL)
```

```
332     pybind_reg = '(/\\*(.*?)\\*/\\s*)?(//\\s*@pybind\\(([^\\n]*)\\)\\s*)?'
333     pybind_attrs_reg = pybind_reg + '(//\\s*@attrs\\(([^\\n]*)\\)\\s*)?'
```
