### ISSUE TITLE
Better compiler path searching with environment varible

### ISSUE THREAD

**Issue by yhl1219** [Jittor/jittor#216]
I'm using `module` for package management on a cluster, the current environment is shown as following:

```
Currently Loaded Modulefiles:
  1) compiler/intel/2019.5.281    4) tools/mumps_seq/5.2.1        7) tools/matlab/R2017a
  2) mpi/intel/2019.5.281         5) tools/superlu/5.2.1          8) compiler/cuda/10.1
  3) tools/tmux/1.8               6) tools/suitesparse/5.6.0      9) interpreter/python/3.7-gpu
```

Note that python 3.7 and `nvcc` 10.1 are both loaded, and currently c/c++ compiler is `icc`, so let's start jittor program

```
[i 0518 20:13:45.097043 52 compiler.py:851] Jittor(1.2.3.8) src: /home/users/$MYNAME$/.local/lib/python3.7/site-packages/jittor
[i 0518 20:13:45.097205 52 compiler.py:852] g++ at /software/local/bin/g++
[i 0518 20:13:45.097302 52 compiler.py:853] cache_path: /home/users/$MYNAME$/.cache/jittor/default/g++
which: no nvcc in (/usr/local/cuda/bin)
[i 0518 20:13:45.195274 52 __init__.py:255] Found gdb(7.6.1) at /bin/gdb.
[i 0518 20:13:45.212988 52 __init__.py:255] Found addr2line(7.3) at /bin/addr2line.
[i 0518 20:13:45.338448 52 compiler.py:893] py_include: -I/software/python/virtualenv/py3.7-gpu/include/python3.7m -I/software/python/virtualenv/py3.7-gpu/include/python3.7m
[i 0518 20:13:45.437864 52 compiler.py:895] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
```

I don't know why jittor is trying to obtain `g++`, which i haven't loaded (so the environment is not correct for g++) and why it hasn't found `nvcc`, maybe compilers should be found by using current environment path

**Comment by yhl1219** [comment]
It seems that my friend also encounter similar problems...
![image](https://user-images.githubusercontent.com/73016480/119260097-d5091c80-bc03-11eb-8de7-7fe071156d91.png)

**Comment by cjld** [comment]
thanks for your feedback, jittor hasn't try install under module environment， it is a just-in-time compilation framework，so g++ and nvcc are needed， could you please try comment out this assertion？

**Comment by cjld** [comment]
jittor hasn't support icc as it backend compiler，please install g++，g++ actually faster than icc in jittor，and less bugs

**Comment by Jittor** [comment]
Any Update?@yhl1219

**Comment by Jittor** [comment]
Jittor now compatible with apt installed `nvidia-cuda-toolkit`
