### ISSUE TITLE
报个论文中的typo

### ISSUE THREAD

**Issue by maxint** [Jittor/jittor#220]
![image](https://user-images.githubusercontent.com/85147/119515808-c27c1800-bda8-11eb-9132-3b3260eef319.png)

**Comment by Jittor** [comment]
谢谢您的反馈，我们更新一下😁



---原始邮件---
发件人: "Naiyang ***@***.***&gt;
发送时间: 2021年5月25日(周二) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jittor/jittor] 报个论文中的typo (#220)

**Comment by maxint** [comment]
赞回复速度！
