### ISSUE TITLE
无网络环境安装jittor：undefined symbol: _ZN6jittor4Node11tflag_count

### ISSUE THREAD

**Issue by FullZing** [Jittor/jittor#229]
执行顺序 
git clone https://github.com/Jittor/jittor.git
sudo pip install ./jittor

python -m jittor.test.test_example

错误 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

注释掉以下代码后
version_file = os.path.join(jittor_path, "version")
if os.path.isfile(version_file) and not os.path.isdir(os.path.join(jittor_path, "src", "__data__")):
    with open(version_file, 'r') as f:
        version = f.read().strip()
    # key = f"{version}-{cc_type}-{'cuda' if has_cuda else 'cpu'}.o"
    key = f"{version}-g++-cpu"
    os_id = os_release["ID"]
    os_key = os_type.get(os_id, "ubuntu")
    if "os_key" in os.environ:
        os_key = os.environ['os_key']
    if platform.machine()=='aarch64':
        os_key += '-aarch64'
    LOG.i("OS type:", os_id, " OS key:", os_key)
    key += '-' + os_key + '.o'
    # TODO: open the website
    extra_obj = os.path.join(cache_path, key)
    url = os.path.join("https://cg.cs.tsinghua.edu.cn/jittor/assets/build/"+key)
    jit_utils.download(url, extra_obj)
    files.append(extra_obj)

另一个错误
ImportError:  .cache/jittor/default/g++/jittor_core.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6jittor4Node11tflag_countE

**Comment by Jittor** [comment]
这段代码是不能注释的，您可以正常打开 https://cg.cs.tsinghua.edu.cn/jittor/ 这个网页吗？这里错误显示 CERTIFICATE_VERIFY_FAILED ， 可能是您SSL证书配置相关issue

**Comment by FullZing** [comment]
某种原因在要安装的环境下无法访问网络， 需要确认一下，这个问题会导致ImportError: .cache/jittor/default/g++/jittor_core.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6jittor4Node11tflag_countE 
如果是的话，或许可以修改源码绕开下载

**Comment by Jittor** [comment]
计图因为有些源码需要网上实时拉下来编译，所以不联网比较麻烦，有三种解决办法：
1. 如果是linux和x86_64的话，可以直接使用docker镜像，教程：https://cg.cs.tsinghua.edu.cn/jittor/tutorial/2020-5-15-00-00-docker/ 。
2. 如果不是，可以吧系统环境+cpu架构告诉我，我去打包，然后发给您
3. 在有网络的环境安装好，然后吧`~/.cache/jittor`文件夹拷贝到无网络的环境下。

有疑问您可以加我微信 randonlang

**Comment by FullZing** [comment]
> 
> 
> 计图因为有些源码需要网上实时拉下来编译，所以不联网比较麻烦，有三种解决办法：
> 
>     1. 如果是linux和x86_64的话，可以直接使用docker镜像，教程：https://cg.cs.tsinghua.edu.cn/jittor/tutorial/2020-5-15-00-00-docker/ 。
> 
>     2. 如果不是，可以吧系统环境+cpu架构告诉我，我去打包，然后发给您
> 
>     3. 在有网络的环境安装好，然后吧`~/.cache/jittor`文件夹拷贝到无网络的环境下。
> 
> 
> 有疑问您可以加我微信 randonlang

有后续完善的办法么？
既然已经开源,  为什么还要去另一个服务器取数据呢？

**Comment by Jittor** [comment]
Jittor是动态编译框架，会实时根据计算设备进行优化，因此许多依赖库还需要根据机器的计算架构，拉取合适的加速库，您现在注释掉了一个库，后面还有好几个库需要下载，所以需要您提供一下架构和系统，这样才能帮您做支持。

我们目前也提供无网络环境的完整x86_64安装包，您这边需要的是x86_64还是什么其他架构呢？我们都可以帮忙做支持

**Comment by FullZing** [comment]
> 
> 
> Jittor是动态编译框架，会实时根据计算设备进行优化，因此许多依赖库还需要根据机器的计算架构，拉取合适的加速库，您现在注释掉了一个库，后面还有好几个库需要下载，所以需要您提供一下架构和系统，这样才能帮您做支持。
> 
> 我们目前也提供无网络环境的完整x86_64安装包，您这边需要的是x86_64还是什么其他架构呢？我们都可以帮忙做支持

已经根据提示都下载下来了， 谢谢你的帮助

**Comment by FullZing** [comment]
另外，从你的反馈来看，jittor 并非全部开源，能简单介绍下哪些开源哪些不开源么 ？
在网站上找不到相关介绍
 
而且以下这些都访问不了了

If you want to know more about Jittor, please check out the notebooks below:

    Quickstart
        Example: Model definition and training
        Basics: Op, Var
        Meta-operator: Implement your own convolution with Meta-operator
    Advanced
        Custom Op: write your operator with C++ and CUDA and JIT compile it
        Profiler: Profiling your model
        Jtune: Tool for performance tuning

Those notebooks can be started in your own computer by python3.7 -m jittor.notebook

**Comment by Jittor** [comment]
谢谢您的反馈，链接刚刚已经修复

**Comment by Jittor** [comment]
这些库是第三方提供的，所以需要额外下载

**Comment by FullZing** [comment]
> 
> 
> 这些库是第三方提供的，所以需要额外下载

既然是第三方库，为何不显式的在仓库里呢？ 
后者也可以像tensorflow 那样，显示的在编译文件里？
