### ISSUE TITLE
Node, Op, Var 关系

### ISSUE THREAD

**Issue by FullZing** [Jittor/jittor#245]
1.  代码： Op 和 Var 继承 Node， 论文里貌似没有提到Node 概念，  为什么呢？
2.  论文里op 分为reindex,  reindex-reduce 和  element-wise 是和以下代码是一一对应的么？
enum OpType {other=0, element=1, broadcast=2, reduce=3};

**Comment by Jittor** [comment]
是的，reindex-reduce就是reduce，reindex就是broadcast，论文中没有提到node，因为他是op和var的基类，var相当与是op的边。
