### ISSUE TITLE
多代码并行的时候sync报错

### ISSUE THREAD

**Issue by sunhm15** [Jittor/jittor#265]
同时运行两个代码的时候第二个代码会报错：

RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync)).

Types of your inputs are:
 self   = Var,
 args   = (),

The function declarations are:
 void sync(bool device_sync = false)

Failed reason:[f 0909 17:29:40.576724 60 executor.cc:527] Execute fused operator(2324/4776) failed: [Op(0x5623cd93d830:0:0:1:i1:o1:s0,broadcast_to->0x5623cd93d8e0),Op(0x5623cf951be0:0:
0:1:i1:o1:s0,broadcast_to->0x5623cf951c90),Op(0x5623cf9534b0:0:0:1:i2:o1:s0,binary.multiply->0x5623cf953540),Op(0x5623cfb976e0:0:0:1:i1:o1:s0,reindex_reduce.add->0x5623cf9565c0),] 

Reason: [f 0909 17:29:39.839614 60 helper_cuda.h:126] CUDA error at ~/.cache/jittor/default/g++/jit/cudnn_conv_backward_x_Tx:float32__Ty:float32__Tw:float32__XFORMAT:abcd__WF ORMAT:oihw__YFOR...hash:74f24b7a5fa4fe17_op.cc:167  code=4( CUDNN_STATUS_INTERNAL_ERROR ) cudnnFindConvolutionBackwardDataAlgorithmEx( handle_, cudnnFdesc, w->ptr<Tw>(), cudnnOdesc, y->ptr<Ty>(), cudnnConvDesc, cudnnIdesc, x->ptr<Tx>(), num_algos, &perf_count, perf_results, ws, max_ws_size) 
[e 0909 17:29:40.891578 60 helper_cuda.h:115] Peek CUDA error at ~/anaconda3/envs/py3/lib/python3.8/site-packages/jittor/src/mem/allocator/cuda_dual_allocator.h:101  code=700 ( cudaErrorIllegalAddress ) _cudaLaunchHostFunc(0, &to_free_allocation, 0) 
terminate called after throwing an instance of 'std::runtime_error'   
what():  [f 0909 17:29:42.170272 60 helper_cuda.h:126] CUDA error at ~/anaconda3/envs/py3/lib/python3.8/site-packages/jittor/extern/cuda/cudnn/src/cudnn_warper.cc:34  code= 4( CUDNN_STATUS_INTERNAL_ERROR ) 
cudnnDestroy(cudnn_handle)

请问下是什么问题？

**Comment by Jittor** [comment]
您留意一下是不是显存用完了呢？因为cudnn运行失败了

**Comment by sunhm15** [comment]
两个代码用的不是同一块GPU，设置cuda_visible了

**Comment by Jittor** [comment]
您可以提供更完整的报错信息吗？再往上翻一页可以看到内存的消耗

**Comment by sunhm15** [comment]
[e 0909 20:20:57.819916 72 executor.cc:521] 
=== display_memory_info ===                                                                                                                                                             
 total_cpu_ram: 125.6GB total_cuda_ram:  23.7GB          
 hold_vars: 1469 lived_vars: 27854 lived_ops: 32988
 update queue: 916/996
 name: sfrl is_cuda: 1 used:  27.2GB(70.5%) unused: 11.37GB(29.5%) total: 38.57GB
 name: sfrl is_cuda: 1 used: 733.6MB(86.8%) unused: 111.4MB(13.2%) total:   845MB
 name: sfrl is_cuda: 0 used: 733.6MB(86.8%) unused: 111.4MB(13.2%) total:   845MB
 name: sfrl is_cuda: 0 used: 2.502MB(83.4%) unused: 509.5KB(16.6%) total:     3MB
 cpu&gpu: 40.22GB gpu: 39.39GB cpu:   848MB
 
name: temp 
 used_memory: 4.883GB 
 unused_memory:  58.5MB 
===========================

似乎确实是超显存了，不过我已经设置了CUDA_VISIBLE为什么还会超呢？

**Comment by Jittor** [comment]
您可以参考一下这个教程，关于如何调试内存不足：https://cg.cs.tsinghua.edu.cn/jittor/assets/docs/Jittor%E8%B0%83%E8%AF%95%E6%8A%80%E5%B7%A7.html#id2

**Comment by sunhm15** [comment]
是临时内存申请导致的，jt.cudnn.set_max_workspace_ratio(0.0) 这个好使了，谢啦
