### ISSUE TITLE
win 10,anaconda版，import jittor报错

### ISSUE THREAD

**Issue by HyperGroups** [Jittor/jittor#280]
PS C:\WINDOWS\system32> python
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import jittor
[i 1103 23:45:34.640000 08 compiler.py:941] Jittor(1.3.1.16) src: D:\ProgramFiles\Anaconda3\lib\site-packages\jittor
[i 1103 23:45:34.664000 08 compiler.py:942] cl at C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1103 23:45:34.664000 08 compiler.py:943] cache_path: C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default
[i 1103 23:45:34.667000 08 install_cuda.py:51] cuda_driver_version: [11, 4, 0]
[i 1103 23:45:34.689000 08 __init__.py:372] Found C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe(11.4.100) at C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe.
[i 1103 23:45:34.844000 08 __init__.py:372] Found gdb(8.1) at D:\ProgramFiles\mingw64\bin\gdb.EXE.
[i 1103 23:45:34.902000 08 __init__.py:372] Found addr2line(2.30) at D:\ProgramFiles\mingw64\bin\addr2line.EXE.
[i 1103 23:45:35.166000 08 compiler.py:993] cuda key:cu11.4.100_sm_86
[i 1103 23:45:35.168000 08 __init__.py:187] Total mem: 47.93GB, using 15 procs for compiling.
[e 1103 23:45:37.213000 08 log.cc:526] cpu_math.cc
D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src\misc\cpu_math.cc(47): error C2065: 'M_PI': undeclared identifier
D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src\misc\cpu_math.cc(53): note: see reference to function template instantiation 'float jittor::calc_erfinv<float>(T)' being compiled
        with
        [
            T=float
        ]
D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src\misc\cpu_math.cc(48): error C2065: 'M_PI': undeclared identifier

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\programfiles\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor_utils\__init__.py", line 157, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 1103 23:45:37.213000 08 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\HyperGroups\.cache\jittor\msvc\VC\include" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src" -I"d:\programfiles\anaconda3\include" -DHAS_CUDA -I"C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\include" -I"D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86"   -O2   -c -Fo: "C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86\obj_files\cpu_math.cc.obj"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\compiler.py", line 1299, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\compiler.py", line 147, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor_utils\__init__.py", line 211, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "D:\ProgramFiles\Anaconda3\lib\multiprocessing\pool.py", line 868, in next
    raise value
RuntimeError: [f 1103 23:45:37.213000 08 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\HyperGroups\.cache\jittor\msvc\VC\include" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\src" -I"d:\programfiles\anaconda3\include" -DHAS_CUDA -I"C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\include" -I"D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86"   -O2   -c -Fo: "C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86\obj_files\cpu_math.cc.obj"

**Comment by WuTianyi321** [comment]
这是由于vc没有M_PI定义造成的，如果想先用上，可以在Python38\Lib\site-packages\jittor\src\misc\cpu_math.cc下修改下代码，把
```
namespace jittor {

#define CENTRAL_RANGE 0.7

template <typename T>
```
改为
```
namespace jittor {

#define CENTRAL_RANGE 0.7
#define M_PI 3.14159265358979323846

template <typename T>
```

**Comment by tupig-7** [comment]
#275

**Comment by WuTianyi321** [comment]
1.3.1.18应该已经修复该问题了，用`python -m pip install jittor -U`更新下再试试？

**Comment by HyperGroups** [comment]
@WuTianyi321 Solved
