### ISSUE TITLE
jt.flags.use_cuda = 1报错

### ISSUE THREAD

**Issue by onlyoh** [Jittor/jittor#292]
## Describe the bug
`python3.7 -m jittor.test.test_cuda` 测试通过，但执行`jt.flags.use_cuda = 1`时，报错

## Full Log
`python3.7 -m jittor.test.test_cuda` 成功的输出：
![image](https://user-images.githubusercontent.com/22839482/155644355-61297896-72b5-4412-8184-efce96ed10ed.png)

执行`jt.flags.use_cuda = 1`的输出：
![image](https://user-images.githubusercontent.com/22839482/155644566-3bbd3f9a-119a-4d74-9fce-a9751637c5d7.png)

## Minimal Reproduce

```python
import jittor as jt
jt.flags.use_cuda = 1
```

## Environment
Python 3.7.12
Ubuntu 18.04.5 LTS
CUDA V11.0.167

请问我可能是哪里设置得不对吗？

**Comment by Jittor** [comment]
没有在您的电脑上检测到显卡，您看下nvidia-smi是否正常，另外删除环境变量unset CUDA_VISIBLE_DEVICES试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月25日(周五) 上午10:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jittor/jittor] jt.flags.use_cuda = 1报错 (Issue #292)




 
Describe the bug
 
python3.7 -m jittor.test.test_cuda 测试通过，但执行jt.flags.use_cuda = 1时，报错
 
Full Log
 
python3.7 -m jittor.test.test_cuda 成功的输出：
 
 
执行jt.flags.use_cuda = 1的输出：
 
 
Minimal Reproduce
 import jittor as jt jt.flags.use_cuda = 1
 
Environment
 
Python 3.7.12
 Ubuntu 18.04.5 LTS
 CUDA V11.0.167
 
请问我可能是哪里设置得不对吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by onlyoh** [comment]
已经解决了，确实是CUDA环境出了问题，谢谢！

**Comment by XChuanLee** [comment]
> 已经解决了，确实是CUDA环境出了问题，谢谢！

请问您是怎么解决的，我也遇到了这个问题
