### ISSUE TITLE
conda环境中使用pip安装出现无法找到glibcxx错误

### ISSUE THREAD

**Issue by sleeplessai** [Jittor/jittor#298]
## 错误
新建了一个conda环境后使用pip安装，测试安装，出现以下错误：
![image](https://user-images.githubusercontent.com/2018063/159275204-ef47d5c7-3a26-4710-906a-43ec020e6dad.png)

## 暂时解决
如果使用系统自带的python和pip安装就没有问题，据悉是conda环境中修改了LD_LIBRARY_PATH导致无法找到glibcxx。
由于对自环境有刚需，所以请教解决方法，或加入conda install支持。

## 环境
system: openSUSE Tumbleweed (latest 5.16)
compiler: gcc/g++11.2.1
cuda/nvcc: 11.6 with update 1
python: 3.8.12
conda 4.11.0/4.8.3

**Comment by cjld** [comment]
谢谢您的反馈，这个主要原因是，jittor会去使用系统自带的g++，系统自带的g++编译出来的jittor同理也需要依赖系统自带的动态链接库，比如libstdc++.so，但是，conda会尝试重载这些系统库，这些系统库和系统的g++不匹配，所以出问题了，解决这个问题可能有几种方法：
1. 不要让conda重载这些库，或者在LD_LIBRARY_PATH中的系统库的优先级提高
2. 让jittor用conda提供的g++来编译，这样c++库就能正确匹配了

**Comment by sleeplessai** [comment]
@cjld 
感谢回复。请问：
1. 如何 “不要让conda重载这些库”？
2. 如何 “让jittor用conda提供的g++来编译”？

**Comment by Jittor** [comment]
1. 您可以调换LD_LIBRARY_PATH中的库路径搜索优先级，或者删除conda里的libc++库。
2. 在conda里面安装一个g++



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月23日(周三) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Jittor/jittor] conda环境中使用pip安装出现无法找到glibcxx错误 (Issue #298)




 
@cjld
 感谢回复。请问：
  
如何 “不要让conda重载这些库”？ 

如何 “让jittor用conda提供的g++来编译”？

**Comment by sleeplessai** [comment]
@Jittor @cjld 


## 建议将jittor团队将jittor加入conda包库中，手工配置子环境太过复杂。


使用内置gcc和nvcc后出现新的错误，
可能又需要从cudnn的库文件拷贝过去才能解决。
然后使用系统的python3.8建立了venv，结果也出现问题。

![image](https://user-images.githubusercontent.com/2018063/159680289-9fde4bbf-4f2f-40c5-a6fc-98c5b214fe9d.png)


> 1. 您可以调换LD_LIBRARY_PATH中的库路径搜索优先级，或者删除conda里的libc++库。 2. 在conda里面安装一个g++
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月23日(周三) 下午5:38 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [Jittor/jittor] conda环境中使用pip安装出现无法找到glibcxx错误 (Issue #298) @cjld 感谢回复。请问： 如何 “不要让conda重载这些库”？ 如何 “让jittor用conda提供的g++来编译”？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by cjld** [comment]
谢谢您的反馈，这些问题其实是和目前已经安装conda环境有关，以及和openSUSE这个操作系统的g++版本有关，比如是conda这个包管理工具内部的so版本控制比较混乱，conda安装cuda和nvcc，经常会安装出不一样的版本，又比如nvcc和gcc之间的版本也不匹配，我建议您按照如下流程安装：
1. 启动一个干净的conda环境，装好python（可选：装好g++，版本不要太高，确保nvcc是支持的，比如g++-7）
2. pip install jittor
3. python -m jittor_utils.install_cuda, 让jittor安装匹配驱动版本的cuda和cudnn
4. python -m jittor.test.test_cuda

需要注意的点：g++版本太高，nvcc版本可能不支持，cudnn也要和cuda版本匹配，cuda版本不能高于驱动版本

**Comment by cjld** [comment]
您如果后续有任何问题，欢迎随时联系，或者加我微信：randonlang，openSUSE这个操作系统的支持还需要测试一下

**Comment by sleeplessai** [comment]
> 

现在已经可以在openSUSE Tumbleweed上使用conda子环境使用jittor。
配置方案有两套，现分享如下：

1. 如果使用了nvidia官方仓库x11-video-nvidiaG05 (470.x) 驱动，这个版本下最高可以支持CUDA 11.3，因此需要使用gcc 7.5，可以使用zypper in gcc7 gcc7-c++直接安装，如有多个版本需要update-alternatives管理。

2. （本人当前配置）使用官方local run手动安装了nvidia 510驱动，这个版本下最高可以支持到 CUDA 11.6，可以使用Tubleweed滚动仓库下的最新的gcc 11.2，默认zypper in gcc gcc-c++即可。

对应了版本后，正常conda create子环境，然后pip install安装jittor即可。
