### ISSUE TITLE
where to find the reference of  "cutt"?

### ISSUE THREAD

**Issue by wu-yy** [Jittor/jittor#3]
https://github.com/Jittor/jittor/blob/4b4ea7bf208034c5cc896c016c73e0c0dd2b485c/python/jittor/compile_extern.py#L179

There is a spelling mistake.

Jittor is cool. And where to find the reference of  "cutt"?

**Comment by cxjyxxme** [comment]
Thanks for your reminder, we have included a reference in the code and fixed the spelling mistake now.
