### ISSUE TITLE
Failed to build from source 

### ISSUE THREAD

**Issue by Leslie-Fang** [Jittor/jittor#31]
Thanks for open-source this project.
I am following the readme in the main-page to build jittor from source(commit-id: 5f84bf11f393ab08342caa23c416d4461ee7243b )
However, I got this error message when I test the installation 
```
export cc_path="/usr/bin/g++"
python -m jittor.test.test_example
....
  File "/usr/local/lib/python3.7/dist-packages/jittor/compiler.py", line 720, in check_cache_compile
    assert jit_utils.cc
AssertionError
```

With preliminary debug, I suspect I failed to import the jit_utils_core
https://github.com/Jittor/jittor/blob/5f84bf11f393ab08342caa23c416d4461ee7243b/python/jittor_utils/__init__.py#L91-L97
And I find jit_utils_core is defined in the jit_utils.cc with pybind.
Any thought to help debug this problem?

**Comment by Jittor** [comment]
Thank you for reporting this issue. This issue is similar to #13 , could you please try:

remove the jittor cache first `rm -rf ~/.cache/jittor`,

and run `python3.7 -m jittor.test.test_example`.

use python3.7 instead of python.

Please feel free to contact us if u have any other problems.

**Comment by Leslie-Fang** [comment]
Thanks for the quick response. It solve the problem.
