### ISSUE TITLE
python -m jittor.test.test_core 出现failed in test_matmul_op,  这样fail是否正常，如果不正常应该如何解决？

### ISSUE THREAD

**Issue by JiangLuo07** [Jittor/jittor#333]
在conda下配置jittor, 以下是我输出的log:

(D:\Anaconda3\jittor_test) python --version
Python 3.9.0

(D:\Anaconda3\jittor_test) python -m pip install jittor
Collecting jittor
  Downloading jittor-1.3.4.13.tar.gz (1.4 MB)
     |████████████████████████████████| 1.4 MB 6.8 MB/s
Collecting numpy
  Downloading numpy-1.22.4-cp39-cp39-win_amd64.whl (14.7 MB)
     |████████████████████████████████| 14.7 MB 819 kB/s
Collecting tqdm
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 3.6 MB/s
Collecting pillow
  Downloading Pillow-9.1.1-cp39-cp39-win_amd64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 6.4 MB/s
Collecting astunparse
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting pywin32>=1.0
  Downloading pywin32-304-cp39-cp39-win_amd64.whl (12.2 MB)
     |████████████████████████████████| 12.2 MB 510 kB/s
Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\anaconda3\jittor_test\lib\site-packages (from astunparse->jittor) (0.37.1)
Collecting six<2.0,>=1.6.1
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: jittor
  Building wheel for jittor (setup.py) ... done
  Created wheel for jittor: filename=jittor-1.3.4.13-py3-none-any.whl size=1773697 sha256=e720878cc3fb6e2345072c2a5ee1e883ca67f87a310a47d77d46cb3c33b8512f
  Stored in directory: c:\users\myname\appdata\local\pip\cache\wheels\b1\67\66\f8ce06964c813dbfdb2a5d41c188caac157fbe14191ce730f2
Successfully built jittor
Installing collected packages: six, colorama, tqdm, pywin32, pillow, numpy, astunparse, jittor
Successfully installed astunparse-1.6.3 colorama-0.4.4 jittor-1.3.4.13 numpy-1.22.4 pillow-9.1.1 pywin32-304 six-1.16.0 tqdm-4.64.0

(D:\Anaconda3\jittor_test) python -m jittor.test.test_core
[i 0603 15:41:54.125114 32 lock.py:85] Create lock file:C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\jittor.lock
[i 0603 15:41:54.140818 32 install_msvc.py:8] Installing MSVC...
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/msvc.zip to C:\Users\myname\.cache\jittor\msvc\msvc.zip
53.3MB [00:07, 7.81MB/s]
[i 0603 15:42:02.796170 32 compiler.py:953] Jittor(1.3.4.13) src: d:\anaconda3\jittor_test\lib\site-packages\jittor
[i 0603 15:42:03.042865 32 compiler.py:954] cl at C:\Users\myname\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0603 15:42:03.042865 32 compiler.py:955] cache_path: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default
[i 0603 15:42:03.042865 32 install_cuda.py:53] cuda_driver_version: [10, 2, 0]
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/cuda10.2_cudnn7_win.zip to C:\Users\myname\.cache\jittor\jtcuda\cuda10.2_cudnn7_win.zip
881MB [01:45, 8.80MB/s]
[i 0603 15:44:00.298303 32 __init__.py:411] Found C:\Users\myname\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe(10.2.89) at C:\Users\myname\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe.
[i 0603 15:44:00.376411 32 compiler.py:1008] cuda key:cu10.2.89
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\jit
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\obj_files
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\gen
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\tmp
[i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\checkpoints
[i 0603 15:44:00.376411 32 __init__.py:227] Total mem: 31.80GB, using 10 procs for compiling.
Compiling jit_utils_core(5/5) used: 2.797s eta: 0.000s
Compiling jittor_core(147/147) used: 23.295s eta: 0.000s
[i 0603 15:44:49.310000 32 jit_compiler.cc:28] Load cc_path: C:\Users\myname\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0603 15:44:49.490000 32 init.cc:62] Found cuda archs: [75,]
[i 0603 15:44:50.259000 32 compile_extern.py:516] mpicc not found, distribution disabled.
[i 0603 15:44:50.259000 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\cutt
[i 0603 15:44:50.259000 32 compile_extern.py:333] Downloading cutt...
Downloading https://codeload.github.com/Jittor/cutt/zip/v1.2 to C:\Users\myname\.cache\jittor\cutt\cutt-1.2.zip
296kB [00:00, 911kB/s]
[i 0603 15:44:50.674000 32 compile_extern.py:346] installing cutt...
Compiling libcutt(9/9) used: 48.963s eta: 0.000s
[i 0603 15:45:40.543000 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\custom_ops
[i 0603 15:45:42.574000 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\mkl
[i 0603 15:45:42.574000 32 compile_extern.py:65] Downloading mkl...
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/dnnl_win_2.2.0_cpu_vcomp.zip to C:\Users\myname\.cache\jittor\mkl\dnnl_win_2.2.0_cpu_vcomp.zip
6.70MB [00:01, 5.53MB/s]
cnn_inference_f32.cpp
Use time: 16.38 ms per iteration.
Example passed on CPU.
Compiling gen_ops_mkl_conv_backward_w_mkl_conv_backward_x_mk___hashc4699b(7/7) used: 2.172s eta: 0.000s
[w 0603 15:45:50.265000 32 compile_extern.py:200] CUDA related path found in LD_LIBRARY_PATH or PATH('此处省略系统环境变量路径'), This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path.
[i 0603 15:45:50.265000 32 compiler.py:34] Create cache dir: C:\Users\myname\.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\cuda
Compiling libcuda_extern(3/3) used: 2.673s eta: 0.000s
[i 0603 15:45:53.403000 32 compile_extern.py:166] Downloading cub...
Downloading https://codeload.github.com/NVIDIA/cub/tar.gz/1.11.0 to C:\Users\myname\.cache\jittor\cub\cub-1.11.0.tgz
424kB [00:00, 553kB/s]
Compiling gen_ops_cudnn_conv3d_backward_w_cudnn_conv3d_backw___hash78c3ee(16/16) used: 2.297s eta: 0.000s
.
Compiling Operators(5/5) used: 4.17s eta:    0s
.Var(52:1:2:2:i1:o1:s0:n0,float32,aa,0)[10,]
Var(54:1:1:1:i1:o1:s0:n0,float32,,0)[10,]
Var(56:1:1:1:i1:o1:s0:n0,float32,,0)[10,]
Var(58:2:1:1:i1:o0:s0:n0,float32,bb,0)[10,]
...F....Var(1029:0:1:0:i0:o1:s1:n1,bool,,1fd182ba460)[10,]
.Var(1073:0:1:0:i0:o1:s1:n1,bool,,1fd182baa60)[10,]
.
Compiling Operators(7/7) used: 5.82s eta:    0s
33 10
...
Compiling Operators(5/5) used: 4.38s eta:    0s
.
======================================================================
FAIL: test_matmul_op (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda3\jittor_test\lib\site-packages\jittor\test\test_core.py", line 70, in test_matmul_op
    assert np.allclose(jtc, c)
AssertionError

----------------------------------------------------------------------
Ran 16 tests in 35.649s

FAILED (failures=1)

**Comment by Jittor** [comment]
谢谢您的反馈，我们检查了下似乎只有细微的精度误差，不影响使用，后续我们会完善该报错信息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月3日(周五) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jittor/jittor] python -m jittor.test.test_core 出现failed in test_matmul_op,  这样fail是否正常，如果不正常应该如何解决？ (Issue #333)




 
在conda下配置jittor, 以下是我输出的log:
 
(D:\Anaconda3\jittor_test) python --version
 Python 3.9.0
 
(D:\Anaconda3\jittor_test) python -m pip install jittor
 Collecting jittor
 Downloading jittor-1.3.4.13.tar.gz (1.4 MB)
 |████████████████████████████████| 1.4 MB 6.8 MB/s
 Collecting numpy
 Downloading numpy-1.22.4-cp39-cp39-win_amd64.whl (14.7 MB)
 |████████████████████████████████| 14.7 MB 819 kB/s
 Collecting tqdm
 Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
 |████████████████████████████████| 78 kB 3.6 MB/s
 Collecting pillow
 Downloading Pillow-9.1.1-cp39-cp39-win_amd64.whl (3.3 MB)
 |████████████████████████████████| 3.3 MB 6.4 MB/s
 Collecting astunparse
 Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
 Collecting pywin32&gt;=1.0
 Downloading pywin32-304-cp39-cp39-win_amd64.whl (12.2 MB)
 |████████████████████████████████| 12.2 MB 510 kB/s
 Requirement already satisfied: wheel<1.0,&gt;=0.23.0 in d:\anaconda3\jittor_test\lib\site-packages (from astunparse-&gt;jittor) (0.37.1)
 Collecting six<2.0,&gt;=1.6.1
 Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
 Collecting colorama
 Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
 Building wheels for collected packages: jittor
 Building wheel for jittor (setup.py) ... done
 Created wheel for jittor: filename=jittor-1.3.4.13-py3-none-any.whl size=1773697 sha256=e720878cc3fb6e2345072c2a5ee1e883ca67f87a310a47d77d46cb3c33b8512f
 Stored in directory: c:\users\myname\appdata\local\pip\cache\wheels\b1\67\66\f8ce06964c813dbfdb2a5d41c188caac157fbe14191ce730f2
 Successfully built jittor
 Installing collected packages: six, colorama, tqdm, pywin32, pillow, numpy, astunparse, jittor
 Successfully installed astunparse-1.6.3 colorama-0.4.4 jittor-1.3.4.13 numpy-1.22.4 pillow-9.1.1 pywin32-304 six-1.16.0 tqdm-4.64.0
 
(D:\Anaconda3\jittor_test) python -m jittor.test.test_core
 [i 0603 15:41:54.125114 32 lock.py:85] Create lock file:C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\jittor.lock
 [i 0603 15:41:54.140818 32 install_msvc.py:8] Installing MSVC...
 Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/msvc.zip to C:\Users\myname.cache\jittor\msvc\msvc.zip
 53.3MB [00:07, 7.81MB/s]
 [i 0603 15:42:02.796170 32 compiler.py:953] Jittor(1.3.4.13) src: d:\anaconda3\jittor_test\lib\site-packages\jittor
 [i 0603 15:42:03.042865 32 compiler.py:954] cl at C:\Users\myname.cache\jittor\msvc\VC_____\bin\cl.exe(19.29.30133)
 [i 0603 15:42:03.042865 32 compiler.py:955] cache_path: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default
 [i 0603 15:42:03.042865 32 install_cuda.py:53] cuda_driver_version: [10, 2, 0]
 Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/cuda10.2_cudnn7_win.zip to C:\Users\myname.cache\jittor\jtcuda\cuda10.2_cudnn7_win.zip
 881MB [01:45, 8.80MB/s]
 [i 0603 15:44:00.298303 32 init.py:411] Found C:\Users\myname.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe(10.2.89) at C:\Users\myname.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe.
 [i 0603 15:44:00.376411 32 compiler.py:1008] cuda key:cu10.2.89
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\jit
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\obj_files
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\gen
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\tmp
 [i 0603 15:44:00.376411 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\checkpoints
 [i 0603 15:44:00.376411 32 init.py:227] Total mem: 31.80GB, using 10 procs for compiling.
 Compiling jit_utils_core(5/5) used: 2.797s eta: 0.000s
 Compiling jittor_core(147/147) used: 23.295s eta: 0.000s
 [i 0603 15:44:49.310000 32 jit_compiler.cc:28] Load cc_path: C:\Users\myname.cache\jittor\msvc\VC_____\bin\cl.exe
 [i 0603 15:44:49.490000 32 init.cc:62] Found cuda archs: [75,]
 [i 0603 15:44:50.259000 32 compile_extern.py:516] mpicc not found, distribution disabled.
 [i 0603 15:44:50.259000 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\cutt
 [i 0603 15:44:50.259000 32 compile_extern.py:333] Downloading cutt...
 Downloading https://codeload.github.com/Jittor/cutt/zip/v1.2 to C:\Users\myname.cache\jittor\cutt\cutt-1.2.zip
 296kB [00:00, 911kB/s]
 [i 0603 15:44:50.674000 32 compile_extern.py:346] installing cutt...
 Compiling libcutt(9/9) used: 48.963s eta: 0.000s
 [i 0603 15:45:40.543000 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\custom_ops
 [i 0603 15:45:42.574000 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\mkl
 [i 0603 15:45:42.574000 32 compile_extern.py:65] Downloading mkl...
 Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/dnnl_win_2.2.0_cpu_vcomp.zip to C:\Users\myname.cache\jittor\mkl\dnnl_win_2.2.0_cpu_vcomp.zip
 6.70MB [00:01, 5.53MB/s]
 cnn_inference_f32.cpp
 Use time: 16.38 ms per iteration.
 Example passed on CPU.
 Compiling gen_ops_mkl_conv_backward_w_mkl_conv_backward_x_mk___hashc4699b(7/7) used: 2.172s eta: 0.000s
 [w 0603 15:45:50.265000 32 compile_extern.py:200] CUDA related path found in LD_LIBRARY_PATH or PATH('此处省略系统环境变量路径'), This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path.
 [i 0603 15:45:50.265000 32 compiler.py:34] Create cache dir: C:\Users\myname.cache\jittor\jt1.3.4\cl\py3.9.0\Windows-10-10.x58\IntelRCoreTMi9xf4\default\cu10.2.89\cuda
 Compiling libcuda_extern(3/3) used: 2.673s eta: 0.000s
 [i 0603 15:45:53.403000 32 compile_extern.py:166] Downloading cub...
 Downloading https://codeload.github.com/NVIDIA/cub/tar.gz/1.11.0 to C:\Users\myname.cache\jittor\cub\cub-1.11.0.tgz
 424kB [00:00, 553kB/s]
 Compiling gen_ops_cudnn_conv3d_backward_w_cudnn_conv3d_backw___hash78c3ee(16/16) used: 2.297s eta: 0.000s
 .
 Compiling Operators(5/5) used: 4.17s eta:    0s
 .Var(52:1:2:2:i1:o1:s0:n0,float32,aa,0)[10,]
 Var(54:1:1:1:i1:o1:s0:n0,float32,,0)[10,]
 Var(56:1:1:1:i1:o1:s0:n0,float32,,0)[10,]
 Var(58:2:1:1:i1:o0:s0:n0,float32,bb,0)[10,]
 ...F....Var(1029:0:1:0:i0:o1:s1:n1,bool,,1fd182ba460)[10,]
 .Var(1073:0:1:0:i0:o1:s1:n1,bool,,1fd182baa60)[10,]
 .
 Compiling Operators(7/7) used: 5.82s eta:    0s
 33 10
 ...
 Compiling Operators(5/5) used: 4.38s eta:    0s
 .
 
FAIL: test_matmul_op (main.TestCore)
 
Traceback (most recent call last):
 File "D:\Anaconda3\jittor_test\lib\site-packages\jittor\test\test_core.py", line 70, in test_matmul_op
 assert np.allclose(jtc, c)
 AssertionError
 
 
Ran 16 tests in 35.649s
 
FAILED (failures=1)

**Comment by chunchunyd** [comment]
遇到了同样的问题，在win11下安装，`python -m jittor.test.test_core`时报错。
```
======================================================================
FAIL: test_matmul_op (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Compiler\Anaconda\envs\jittor\lib\site-packages\jittor\test\test_core.py", line 70, in test_matmul_op
    assert np.allclose(jtc, c)
AssertionError

----------------------------------------------------------------------
Ran 16 tests in 0.824s

FAILED (failures=1)

**Comment by Jittor** [comment]
您可以更新最新版本jittor，1.3.4.14
