### ISSUE TITLE
jittor 安装错误

### ISSUE THREAD

**Issue by KevinZzz35** [Jittor/jittor#361]
## Describe the bug
安装的github 上面最新的，运行 jittor.test.test_example 会报错
## Full Log
python -m jittor.test.test_example                                                                                                          ─╯
[i 0729 23:27:53.121185 08 compiler.py:955] Jittor(1.3.4.19) src: /home/zhangkai01/.conda/envs/MODNET/lib/python3.9/site-packages/jittor
[i 0729 23:27:53.123715 08 compiler.py:956] g++ at /opt/cuda/bin/g++(11.3.0)
[i 0729 23:27:53.123777 08 compiler.py:957] cache_path: /home/zhangkai01/.cache/jittor/jt1.3.4/g++11.3.0/py3.9.12/Linux-5.16.10-xaa/IntelRCoreTMi7x8f/default
[i 0729 23:27:53.126555 08 __init__.py:411] Found nvcc(11.7.64) at /opt/cuda/bin/nvcc.
[i 0729 23:27:53.180516 08 __init__.py:411] Found gdb(11.2) at /usr/bin/gdb.
[i 0729 23:27:53.184289 08 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0729 23:27:53.253711 08 compiler.py:1010] cuda key:cu11.7.64_sm_86
[i 0729 23:27:53.373248 08 __init__.py:227] Total mem: 62.53GB, using 16 procs for compiling.
[i 0729 23:27:53.418286 08 jit_compiler.cc:28] Load cc_path: /opt/cuda/bin/g++
[1]    60333 IOT instruction (core dumped)  python -m jittor.test.test_example

![image](https://user-images.githubusercontent.com/22927025/181793639-ca1e4bb1-03a9-42bb-81b7-98f270003465.png)
## Minimal Reproduce
python3.9 
cuda 11.7
cudnn 8.4
Reproduce this error with a file or several lines of code. 
If it is not possible, leave it blank.

## Expected behavior

If you are submitting an issue for the first time, please refer to [our guideline](https://github.com/Jittor/jittor/issues/238)

**Comment by Jittor** [comment]
您方便运行`gdb_attach=1 python -m jittor.test.test_example`，然后按c吗，然后把输出的信息贴一下
您还可以加计图开发者交流群，我帮您远程调试一下

**Comment by KevinZzz35** [comment]
> 

搞定了，谢谢！

**Comment by hanhuili** [comment]
> > 
> 
> 搞定了，谢谢！

老哥我也遇到这个问题，怎么解决的？

**Comment by KevinZzz35** [comment]
> > > 
> > 
> > 
> > 搞定了，谢谢！
> 
> 老哥我也遇到这个问题，怎么解决的？

应该是从arch 换成 ubuntu 。太久了  记不得了

**Comment by hanhuili** [comment]
> > > > 
> > > 
> > > 
> > > 搞定了，谢谢！
> > 
> > 
> > 老哥我也遇到这个问题，怎么解决的？
> 
> 应该是从arch 换成 ubuntu 。太久了 记不得了

好的，谢谢老哥

**Comment by krauwu** [comment]
同样的问题，有什么解决方法吗
