### ISSUE TITLE
请问ImageNet预训练模型的下载链接有吗

### ISSUE THREAD

**Issue by ga546** [Jittor/jittor#379]
ImageNet预训练模型的下载链接

**Comment by zhouwy19** [comment]
Hi, which model do you want?

**Comment by ga546** [comment]
> Hi, which model do you want?

resnet50的预训练模型，大佬可以给个链接吗？

**Comment by lzhengning** [comment]
使用 jittor.models.resnet50 时设置 pertained 为 True 即可。
https://cg.cs.tsinghua.edu.cn/jittor/assets/docs/jittor.models.html?highlight=resnet#jittor.models.resnet50
