### ISSUE TITLE
/usr/include/stdio.h(189): error: attribute "__malloc__" does not take arguments

### ISSUE THREAD

**Issue by linkerlin** [Jittor/jittor#431]
## Describe the bug
运行： python3 -m jittor.test.test_cudnn_op
出错。
在执行了 python3 -m jittor_utils.install_cuda
之后。

## Full Log
python3 -m jittor_utils.install_cuda
[i 0416 18:23:16.363854 44 install_cuda.py:93] cuda_driver_version: [12, 1]
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/cuda11.2_cudnn8_linux.tgz to /home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux.tgz
1.62GB [00:36, 47.4MB/s]                                                                            
[i 0416 18:24:10.920513 44 install_cuda.py:162] nvcc is installed at /home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc
linker@amd5900x:~$ python3 -m jittor.test.test_cudnn_op
[i 0416 18:24:25.478285 84 compiler.py:955] Jittor(1.3.7.13) src: /home/linker/.local/lib/python3.10/site-packages/jittor
[i 0416 18:24:25.480354 84 compiler.py:956] g++ at /usr/bin/g++(11.3.0)
[i 0416 18:24:25.480408 84 compiler.py:957] cache_path: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default
[i 0416 18:24:25.493881 84 install_cuda.py:93] cuda_driver_version: [12, 1]
[i 0416 18:24:25.494083 84 install_cuda.py:81] restart /usr/bin/python3 ['-m', 'jittor.test.test_cudnn_op']
[i 0416 18:24:25.550576 60 compiler.py:955] Jittor(1.3.7.13) src: /home/linker/.local/lib/python3.10/site-packages/jittor
[i 0416 18:24:25.552010 60 compiler.py:956] g++ at /usr/bin/g++(11.3.0)
[i 0416 18:24:25.552083 60 compiler.py:957] cache_path: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default
[i 0416 18:24:25.565247 60 install_cuda.py:93] cuda_driver_version: [12, 1]
[i 0416 18:24:25.567915 60 __init__.py:411] Found /home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc(11.2.152) at /home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc.
[i 0416 18:24:25.614044 60 __init__.py:411] Found gdb(12.1) at /usr/bin/gdb.
[i 0416 18:24:25.615437 60 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0416 18:24:25.680770 60 compiler.py:1010] cuda key:cu11.2.152_sm_86
[i 0416 18:24:25.699270 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86
[i 0416 18:24:25.699458 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/jit
[i 0416 18:24:25.699586 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/obj_files
[i 0416 18:24:25.699709 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/gen
[i 0416 18:24:25.699823 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/tmp
[i 0416 18:24:25.699938 60 compiler.py:34] Create cache dir: /home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/checkpoints
[i 0416 18:24:30.439637 60 __init__.py:227] Total mem: 125.73GB, using 16 procs for compiling.
/usr/include/stdio.h(189): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(201): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(223): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(260): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(285): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(294): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(303): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(309): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(315): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(830): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(566): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(570): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(799): error: attribute "__malloc__" does not take arguments

/usr/include/c++/11/type_traits(1406): error: type name is not allowed

/usr/include/c++/11/type_traits(1406): error: type name is not allowed

/usr/include/c++/11/type_traits(1406): error: identifier "__is_same" is undefined

/usr/include/wchar.h(155): error: attribute "__malloc__" does not take arguments

/usr/include/wchar.h(582): error: attribute "__malloc__" does not take arguments

/home/linker/.local/lib/python3.10/site-packages/jittor/src/misc/cstr.h(19): error: no instance of overloaded function "std::unique_ptr<_Tp [], _Dp>::reset [with _Tp=char, _Dp=std::default_delete<char []>]" matches the argument list
            argument types are: (char *)
            object type is: jittor::unique_ptr<char []>

/home/linker/.local/lib/python3.10/site-packages/jittor/src/misc/cstr.h(25): error: no instance of overloaded function "std::unique_ptr<_Tp [], _Dp>::reset [with _Tp=char, _Dp=std::default_delete<char []>]" matches the argument list
            argument types are: (char *)
            object type is: jittor::unique_ptr<char []>

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6620): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6625): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6630): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6635): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6640): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6646): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6650): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6654): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6751): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6756): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6761): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6766): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6771): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6777): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6781): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6785): here

36 errors detected in the compilation of "/home/linker/.local/lib/python3.10/site-packages/jittor/src/misc/nan_checker.cu".
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/linker/.local/lib/python3.10/site-packages/jittor_utils/__init__.py", line 197, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0416 18:24:37.757675 60 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc"  "/home/linker/.local/lib/python3.10/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/linker/.local/lib/python3.10/site-packages/jittor/src" -I/usr/include/python3.10 -I/usr/include/python3.10 -DHAS_CUDA -DIS_CUDA -I"/home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/home/linker/.local/lib/python3.10/site-packages/jittor/extern/cuda/inc"   -I"/home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86"   -O2   -c -o "/home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/linker/.local/lib/python3.10/site-packages/jittor/extern/cuda/inc" 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/linker/.local/lib/python3.10/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/linker/.local/lib/python3.10/site-packages/jittor/compiler.py", line 1353, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/home/linker/.local/lib/python3.10/site-packages/jittor/compiler.py", line 151, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/home/linker/.local/lib/python3.10/site-packages/jittor_utils/__init__.py", line 251, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
RuntimeError: [f 0416 18:24:37.757675 60 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc"  "/home/linker/.local/lib/python3.10/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/linker/.local/lib/python3.10/site-packages/jittor/src" -I/usr/include/python3.10 -I/usr/include/python3.10 -DHAS_CUDA -DIS_CUDA -I"/home/linker/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/home/linker/.local/lib/python3.10/site-packages/jittor/extern/cuda/inc"   -I"/home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86"   -O2   -c -o "/home/linker/.cache/jittor/jt1.3.7/g++11.3.0/py3.10.6/Linux-5.19.0-3x1b/AMDRyzen95900Xx4a/default/cu11.2.152_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/linker/.local/lib/python3.10/site-packages/jittor/extern/cuda/inc"

**Comment by linkerlin** [comment]
但是这台机器，我是用来跑LLM的，日常PyTorch跑没有问题，CUDA也OK的。

**Comment by linkerlin** [comment]
python3 cuda_cudnn_checker.py 
CUDA is available
CUDA version: 11.8
GPU 1 : NVIDIA GeForce RTX 3090
cuDNN is enabled
cuDNN version: 8700

**Comment by gn-share** [comment]
我也遇到了这个错误，谁能解答一下啊

**Comment by gn-share** [comment]
这个问题我的解决了，是因为他这个编译过程中的nvcc路径和我本机实际的路径不对导致的

通过 export nvcc_path="/usr/local/cuda-12.0/bin/nvcc" 设置下nvcc的路径，就可以解决，nvcc路径 我是通过 which nvcc 查看的。

**Comment by SCZwangxiao** [comment]
I've tried export nvcc_path mentioned by @gn-share. The problem is solved. However, another problem arise:
```bash
OSError: /***/miniconda3/envs/next3d/lib64/libcudart.so: cannot open shared object file: No such file or directory
```

What a messy project!

**Comment by SCZwangxiao** [comment]
Found the solution. 

Replace `cuda_lib = os.path.abspath(os.path.join(cuda_dir, "..", "lib64"))` into `cuda_lib = os.path.abspath(os.path.join(cuda_dir, "..", "lib"))`

in `check_cuda()` from `"/***/miniconda3/envs/next3d/lib/python3.9/site-packages/jittor/compiler.py"`

**Comment by LDYang694** [comment]
g++版本过高导致的 我改使用g++9.4.0就没问题了
