### ISSUE TITLE
已放弃 核心已转储

### ISSUE THREAD

**Issue by liujianzhi** [Jittor/jittor#444]
## Describe the bug
您好，运行jittor时，出现下列问题
python -m jittor.test.test_example
[i 0525 13:49:43.769016 08 compiler.py:955] Jittor(1.3.7.16) src: /home/liujianzhi/anaconda3/envs/jittor/lib/python3.11/site-packages/jittor
[i 0525 13:49:43.772667 08 compiler.py:956] g++ at /usr/bin/g++(9.3.0)
[i 0525 13:49:43.772824 08 compiler.py:957] cache_path: /home/liujianzhi/.cache/jittor/jt1.3.7/g++9.3.0/py3.11.3/Linux-5.11.0-4x1a/IntelRXeonRCPUx00/default
[i 0525 13:49:43.776610 08 __init__.py:411] Found nvcc(11.4.120) at /usr/local/cuda/bin/nvcc.
[i 0525 13:49:43.851252 08 __init__.py:411] Found gdb(9.2) at /usr/bin/gdb.
[i 0525 13:49:43.855583 08 __init__.py:411] Found addr2line(2.34) at /usr/bin/addr2line.
[i 0525 13:49:44.359210 08 compiler.py:1010] cuda key:cu11.4.120_sm_86
[i 0525 13:49:44.560204 08 __init__.py:227] Total mem: 251.78GB, using 16 procs for compiling.
[i 0525 13:49:44.690975 08 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
已放弃 (核心已转储)

**Comment by krauwu** [comment]
请问解决了吗？

**Comment by liujianzhi** [comment]
没有 我放弃了发自我的 iPhone在 2024年4月20日，19:44，songbur ***@***.***> 写道：﻿
请问解决了吗？
