### ISSUE TITLE
Cannot build documentation with Python 3.11 or 3.12

### ISSUE THREAD

**Issue by bkmgit** [Jittor/jittor#492]
## Describe the bug
When building documentation using sphinx, for release 1.3.4.1 get an error
```
invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
```
## Full Log

Full log is available at 
https://kojipkgs.fedoraproject.org//work/tasks/273/106030273/build.log

## Minimal Reproduce

```
sudo dnf install wget sphinx-build python3-devel gcc-c++
wget https://github.com/jittor/jittor/archive/1.3.4.1/jittor-1.3.4.1.tar.gz
tar -xf jittor-1.3.4.1.tar.gz
cd jittor-1.3.4.1
cd doc
sphinx-build -b man source man
```

## Expected behavior
Expect to get documentation.

**Comment by LDYang694** [comment]
We prepared the official documentation:
[https://cg.cs.tsinghua.edu.cn/jittor/assets/docs/index.html](https://cg.cs.tsinghua.edu.cn/jittor/assets/docs/index.html)
