### ISSUE TITLE
python3.7 -m jittor.test.test_example正常运行，但是python3.7 -m jittor.test.test_cuda 报错，请作者帮忙分析解决一下，万分感激

### ISSUE THREAD

**Issue by XD-mu** [Jittor/jittor#501]
[i 0408 04:37:28.679013 04 compiler.py:956] Jittor(1.3.9.2) src: /home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor
[i 0408 04:37:28.685029 04 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0408 04:37:28.685113 04 compiler.py:958] cache_path: /home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default
[i 0408 04:37:28.715508 04 install_cuda.py:93] cuda_driver_version: [11, 7]
[i 0408 04:37:28.722594 04 __init__.py:412] Found /home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc(11.2.152) at /home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc.
[i 0408 04:37:28.800993 04 __init__.py:412] Found gdb(8.1.1) at /usr/bin/gdb.
[i 0408 04:37:28.808537 04 __init__.py:412] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0408 04:37:28.945857 04 compiler.py:1011] cuda key:cu11.2.152_sm_75
[i 0408 04:37:29.408868 04 __init__.py:227] Total mem: 251.53GB, using 16 procs for compiling.
[i 0408 04:37:29.528834 04 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0408 04:37:29.651946 04 init.cc:63] Found cuda archs: [75,]
[i 0408 04:37:31.289525 04 cuda_flags.cc:49] CUDA enabled.
.[i 0408 04:37:31.312108 04 cuda_flags.cc:49] CUDA enabled.
.[i 0408 04:37:31.314113 04 cuda_flags.cc:49] CUDA enabled.
/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/cuda_atomic.h(111): error: identifier "__bfloat16_as_ushort" is undefined

/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/cuda_atomic.h(113): error: identifier "__ushort_as_bfloat16" is undefined

2 errors detected in the compilation of "/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75/jit/__opkey0_array__T_int32__o_2__opkey1_binary__Tx_int32__Ty_int32__Tz_int32__OP_add__opkey2____hash_861eebc2e1f0c5c2_op.cc".
E[i 0408 04:37:32.380234 04 cuda_flags.cc:49] CUDA enabled.
.s
======================================================================
ERROR: test_cuda_fused_op (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/test/test_cuda.py", line 108, in test_cuda_fused_op
    ((a+a)*2).data
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.data)).

Types of your inputs are:
 self   = Var,

The function declarations are:
 inline DataView data()

Failed reason:[f 0408 04:37:32.377300 04 parallel_compiler.cc:331] Error happend during compilation:
 [Error] source file location:/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75/jit/__opkey0_array__T_int32__o_2__opkey1_binary__Tx_int32__Ty_int32__Tz_int32__OP_add__opkey2____hash_861eebc2e1f0c5c2_op.cc
Compile fused operator(0/1)failed:[Op(18:0:1:1:i0:o1:s0:g1,array->19),Op(16:0:1:1:i2:o1:s0:g1,binary.add->17),Op(22:0:1:1:i1:o1:s0:g1,broadcast_to->23),Op(24:0:1:1:i2:o1:s0:g1,binary.multiply->25),]

Reason: [f 0408 04:37:32.376684 04 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc" "/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75/jit/__opkey0_array__T_int32__o_2__opkey1_binary__Tx_int32__Ty_int32__Tz_int32__OP_add__opkey2____hash_861eebc2e1f0c5c2_op.cc"      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/src" -I/home/mcy/miniconda3/envs/jittor/include/python3.7m -I/home/mcy/miniconda3/envs/jittor/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc"  -lcudart -L"/home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64" -Xlinker -rpath="/home/mcy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64"  -I"/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75" -L"/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75" -Xlinker -rpath="/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75" -L"/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default" -Xlinker -rpath="/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default"  -l:"jit_utils_core.cpython-37m-x86_64-linux-gnu".so  -l:"jittor_core.cpython-37m-x86_64-linux-gnu".so  -x cu --cudart=shared -ccbin="/usr/bin/g++" --use_fast_math  -w  -I"/home/mcy/miniconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc"  -arch=compute_75  -code=sm_75   -o "/home/mcy/.cache/jittor/jt1.3.9/g++7.5.0/py3.7.12/Linux-5.4.0-14xe3/IntelRXeonRGolx80/66b4/default/cu11.2.152_sm_75/jit/__opkey0_array__T_int32__o_2__opkey1_binary__Tx_int32__Ty_int32__Tz_int32__OP_add__opkey2____hash_861eebc2e1f0c5c2_op.so"

----------------------------------------------------------------------
Ran 5 tests in 1.254s

FAILED (errors=1, skipped=1)

我该如何解决？

**Comment by LDYang694** [comment]
请更新到最新版本 已修复

**Comment by enemy1205** [comment]
> 请更新到最新版本 已修复

即使使用了最新版本也还是遇到了该情况

环境
python环境完全按手动安装配置

Ubuntu 20.04
cuda_11.3.r11.3/
Driver Version: 535.171.04

四卡

**Comment by enemy1205** [comment]
> > > 请更新到最新版本 已修复
> > 
> > 
> > 即使使用了最新版本也还是遇到了该情况
> > 环境 python环境完全按手动安装配置
> > Ubuntu 20.04 cuda_11.3.r11.3/ Driver Version: 535.171.04
> > 四卡
> 
> 使用的是什么显卡？最好贴出具体的报错信息

四卡1080Ti，具体报错如题主一样
![image](https://github.com/Jittor/jittor/assets/30740917/7aa17fcf-4cdc-4219-9003-af80e79189a0)

**Comment by Leg-end** [comment]
同问， 在执行命令python -m jittor.test.test_resnet时报错
openMPI已安装， 版本为4.0.3
jittor 版本 1.3.8.5
4卡P100
![image](https://github.com/Jittor/jittor/assets/31924601/b6fe8b37-044b-4bfa-8625-7e61188bdee0)
![image](https://github.com/Jittor/jittor/assets/31924601/971f6f10-86bb-47ee-8b53-966dbbb118cc)
![image](https://github.com/Jittor/jittor/assets/31924601/937ae4ac-7692-44e8-929e-b8d0abf85783)

**Comment by LDYang694** [comment]
针对p100,1080等显卡出现的兼容性问题已在最新commit修复
