### ISSUE TITLE
jittor如何查看模型使用的设备

### ISSUE THREAD

**Issue by f-chen165** [Jittor/jittor#504]
## Describe the bug
A clear and concise description of what the bug is. 使用中文也可以。

## Full Log

Provide a full log of Jittor execution, Jittor will log environment information which help us to locate your bugs. Provide a screenshot is also acceptable.

## Minimal Reproduce

Reproduce this error with a file or several lines of code. 
If it is not possible, leave it blank.

## Expected behavior

If you are submitting an issue for the first time, please refer to [our guideline](https://github.com/Jittor/jittor/issues/238)

**Comment by LDYang694** [comment]
如果使用了jt.flags.use_cuda=1则默认所有的模型全部使用gpu，如果想指定某个gpu，使用CUDA_VISIBLE_DEVICES环境变量
