### ISSUE TITLE
if we can create an installation for Mac OS

### ISSUE THREAD

**Issue by tomzhang** [Jittor/jittor#6]

**Comment by cxjyxxme** [comment]
Sorry，there are currently no plans to support it, more systems may be supported after the ubuntu version is more stable. :)

**Comment by xxg1413** [comment]
在MacOS上可以使用PIP安装
直接clone项目并`sudo pip3 install ./jittor`进行安装。

```
[Desktop] python3                              
Python 3.7.4 (default, Oct  9 2019, 06:58:09)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jittor
>>> dir(jittor)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>>

```
也可以在MacOS上使用docker来进行安装。

**Comment by lzhengning** [comment]
Jittor supports macOS now, on both intel and M1 platform. The install instruction is provided in [README](https://github.com/Jittor/jittor#macOS-install). 

Mac users can have a try, and are welcomed to open issues when encountering any problems.
