### ISSUE TITLE
import jittor as jt 过程中运行git branch这个设定真是鸡肋

### ISSUE THREAD

**Issue by WooyoungLi** [Jittor/jittor#66]
import jittor as jt 过程中运行git branch这个设定真是鸡肋，怎样去掉？如下是import jittor as jt 过程中的输出：
[i 0421 10:18:02.257445 28 v1 __init__.py:102] Run cmd: which g++
[i 0421 10:18:02.260915 28 v1 __init__.py:102] Run cmd: /usr/bin/g++ --version
[i 0421 10:18:02.265384 28 __init__.py:183] Found g++(9.3.0) at /usr/bin/g++.
[i 0421 10:18:02.267761 28 v1 __init__.py:102] Run cmd: git branch
fatal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。

**Comment by cjld** [comment]
您好，该报错信息已经在最新的master分支修复，请您尝试删除旧版本jittor并且安装最新版本：
`python3.7 -m pip uninstall jittor && python3.7 -m pip install git+https://github.com/Jittor/jittor.git`
