### ISSUE TITLE
没有Windows支持别瞎出大作业

### ISSUE THREAD

**Issue by duanqn** [Jittor/jittor#67]
大家在家上网课已经很不容易了，这个jittor只支持Linux，不适宜作为大作业的一部分。隔壁自动化系已经翻车了，图形学这课可别给贵系丢人。

**Comment by duanqn** [comment]
不同OS倾向及跨OS人士，都有个人天分同才华，唔应该受到歧视。不歧视，多包容，不同OS倾向及跨OS人士。

**Comment by cjld** [comment]
这位同学您好，这学期图形学大作业还是光线追踪。jittor目前支持Windows， 支持方式是WSL，WSL的安装方法请参考微软官网：https://docs.microsoft.com/en-us/windows/wsl/install-win10
如果您在使用的过程中碰到任何问题欢迎反馈。

**Comment by cjld** [comment]
图形学课程坚持以让同学们学习图形学基础知识和了解前沿进展为己任，不会本末倒置的，请各位同学放心。目前计图开发主力是实验室的博士生， 同时我们也十分欢迎对计图感兴趣的同学加入开发。

**Comment by duanqn** [comment]
谢谢解答！
