### ISSUE TITLE
性能测试及显存占用

### ISSUE THREAD

**Issue by feihuidiqiu** [Jittor/jittor#97]
```python
import os
import sys
import numpy as np
import jittor as jt
import jittor.models as jtmodels
import json
import time
jt.flags.use_cuda=1
a=np.random.rand(5, 3,512,512).astype('float32')
inputs=jt.array(a)
res=m(inputs)
t=time.time()
r=[]
for i in range(10):
    a=np.random.rand(5, 3,512,512).astype('float32')
    inputs=jt.array(a)
    res=m(inputs)
    r.append(res.max().numpy().tolist()[0])
print(time.time()-t)
```
在v100卡上对比当前版本的计图和pytorch1.4，
同样的程序计图平均在960ms，pytorch在950ms左右，感觉没有起到加速效果
同时计图占用了15516M显存，gc后会减少到6736M，显存占用较大，
请问针对这种推理方式有优化使用的方式么

**Comment by cjld** [comment]
您好，关于测试时间的方法请参考： https://cg.cs.tsinghua.edu.cn/jittor/tutorial/2020-5-2-16-43-pytorchconvert/#%E7%AC%AC%E4%B8%89%E9%83%A8%E5%88%86-%E6%97%B6%E9%97%B4%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%96%B9%E6%B3%95

关于显存占用，计图会在显存充足的情况下尽量多使用显存，所以直接对比显存消耗不是很具有可比性，更好的方法是测试同样的计算设备，最大能开到多大的batch size

**Comment by cjld** [comment]
我们看到您的代码并没有进行热身，没有热身的话时间测试是不准确的，您可以试试如下代码：
```python
import os
import sys
import numpy as np
import jittor as jt
import jittor.models as jtmodels
import json
import time
jt.flags.use_cuda=1
a=np.random.rand(5, 3,512,512).astype('float32')
inputs=jt.array(a)
res=m(inputs)
print(res.max().data[0])
t=time.time()
r=[]
for i in range(10):
    a=np.random.rand(5, 3,512,512).astype('float32')
    inputs=jt.array(a)
    res=m(inputs)
    r.append(res.max().data[0])
print(time.time()-t)
```

**Comment by feihuidiqiu** [comment]
@cjld 感谢解答，
```python
t=time.time()
r=[]
for i in range(10):
    a=np.random.rand(5, 3,512,512).astype('float32')
    inputs=jt.array(a)
    res=m(inputs)
    r.append(res.max().data[0])
print(time.time()-t)
```
热身问题的确没注意，960ms是多次重复执行上面的代码片段观察的平均时间，第一次运行时间会比较长

官网中的benchmark测试方法，的确会有速度提升，暂时不考虑训练环境，在实际推断服务使用中，一般batch都为1，而且提供服务时单次请求会返回结果，代码中用r.append(res.max().data[0])进行模拟，针对这种推断场景目前是否还无法支持加速

在推断场景中，有时会在单卡部署多个服务，一个服务占用太多显存会对其他服务造成影响，有没有设置可以尽量降低占用呢

**Comment by cjld** [comment]
感谢您的反馈。
如果是这样的话可以吧inputs停止梯度：`inputs.stop_grad()`，还有模块切换成inference模式`m.eval()`, 应该可以节省很多显存

**Comment by cjld** [comment]
还有一个可以加速的地方是使用计图提供的异步接口：
```python
t=time.time()
r=[]
for i in range(10):
    a=np.random.rand(5, 3,512,512).astype('float32')
    inputs=jt.array(a).stop_grad()
    res=m(inputs)
    res.fetch(lambda x: r.append(x))
jt.sycn_all(True)
print(time.time()-t)
```

**Comment by feihuidiqiu** [comment]
感谢大神解答，
在相同eval、no_grad模式下与pytorch对比测试，性能提升在50%到70%，
显存占用基本一致。
